permissions:
  contents: write

name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch:

permissions:
  contents: write # Permissão essencial para que o bot possa escrever no repositório

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate the snake animation
        uses: Platane/snk@master
        with:
          github_user_name: gabrielc-neto # Seu nome de usuário
          outputs: |
            assets/github-snake.svg
            assets/github-snake-dark.svg?palette=github-dark
            assets/github-snake.gif
            
      - name: Commit and push the snake
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add assets/
          git commit -m "feat: generate GitHub snake animation" || echo "No changes to commit"
          git push
