name: Generate Snake Chart

on:
  schedule:
    - cron: "0 0 * * *"  # executa todo dia à meia-noite (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Snake Generator
        uses: Platane/snk@v3
        with:
          github_user_name: gabrielc-neto
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
