name: Generate Snake
permissions:
  contents: write
on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: gabrielc-neto
          outputs: |
            ./dist/github-snake-dark.svg
            ./dist/github-snake.gif
            ./dist/github-snake-light.svg?palette=github-light

      - name: Push to repo
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
